### ISSUE TITLE
Auto-recording via stand-by.

### ISSUE THREAD

**Issue by ghost** [RoyalFlyBy/ChaturbateDownloader#1] opened 2020-01-04 13:16 UTC
I'd an idea, but I don't know if it's possible to do it, @RoyalFlyBy🤔.
When using ChaturbateDownloader but the «_Room is currently offline_», the result is as follows.
![Immagine](https://user-images.githubusercontent.com/58144783/71765725-79e46600-2ef8-11ea-8ee7-5981fa638d1c.png)
Imagine that You want to follow the Cam Shows of a performer who broadcasts from a very different time zone: f.e, I live in Central European Time, but I would to record videos of a model from Chicago or Sydney🙄; obviously I **won't** be able to be physically in front of my pc (like at _night_ 😴) to activate the [.exe](https://github.com/RoyalFlyBy/ChaturbateDownloader/blob/master/chaturbateDownloader.exe) when the «_Room is online_». I was wondering if **it would be possible to add monitoring functionality so that if a favorite model came online, the application automatically started recording**.
A sort of "stand-by function".
Please, see [this issue](https://github.com/2MinhetNguyles/Chaturbate-Recorder-GUI/issues/3) and [this discussion](https://github.com/2MinhetNguyles/Chaturbate-Recorder-GUI/commit/13e63af2346de977da8424a709f3c3ab962abb6a#commitcomment-36058791).
The result would look like this, more or less (_hypothetical screen_).
![Immagine](https://user-images.githubusercontent.com/58144783/71766058-1fe59f80-2efc-11ea-8aea-69549defcb47.png)
Do You think it's possible to program a similar enhancement?

**Comment by RoyalFlyBy** [comment] 2020-01-24 18:14
I was working on a solution for that but it would probably not be able to work as simple as that.
In order to see if a model is online the program would need to issue a request to obtain updated information which in turn can be filtered by Chaturbate for abnormal behavior.

The solution I was working on involved using an account and the subscribe feature and then poll the email service (I would use a temporary mail service) for a notification a model is online and then start a video capture thread based off that.

If you're interested in that I can work on it again, maybe merge it into this program but ETA will be about 2 weeks.

Sorry for my very late reply, ever since my travels this account has been acting up when I try to log in but I finally got it to work again

**Comment by ghost** [comment] 2020-01-27 15:08
I think Your solution is intriguing: in fact, I receive a email notification every time the model goes online (the «Room» opens at **1.00 AM**: _I'm sleeping at these hours!!_ 😨). However, my account isn't «verified» through photography of identity card. If it were a fairly intuitive solution that works even with «unverified» accounts, I think it would be very great🤗!

Even **if it takes two weeks** -or something more- **it doesn't matter**: Microsoft is forcing me to change my PC (bought in 2008), sofware 'n' hardware, so February will be a turbulent month ...

**Comment by RoyalFlyBy** [comment] 2020-02-09 04:57
I finally got some major advancements in the project, I will probably release it in a separate repository at first so it doesn't accidentally mess with the main program.

Yes the solution would be much better with any type of account honestly, if I were to ban bots I would look for the most repetitive HTTP requests with no reason behind them.

This method I will also implement in a similar program but for YouTube on my main account (however that project is even harder to do as of yet since I haven't gotten authentication to fully work yet)

It would work by relying on the email notifications sent by Chaturbate to an email inbox, as soon as it sees the message it will start downloading the stream until the model goes offline. Email providers expect a lot of repetitive requests for checking if there are new emails so it doesn't look suspicious for them and Chaturbate wouldn't be able to tell. For all they know you are just a very enthusiastic fan that joins streams instantly.

**Comment by RoyalFlyBy** [comment] 2020-02-09 05:00
My point of view isn't shared by a lot of people. (hence you're pretty much guaranteed to get ignored by people by telling them about this type of solution)
 I got most my experience from reverse engineering and botting games and other services who all banned bots actively so I tend to try to make my programs work around that even before they ban anyone using my programs.

**Comment by ghost** [comment] 2020-02-13 12:44
So I, meanwhile, wait patiently You news, **@RoyalFlyBy**: I'm very interested in ...

**Comment by RoyalFlyBy** [comment] 2020-02-13 16:29
Today will I will be compiling the very first test build to see it in action.
I do have to note I had to create a new account because my email notifications weren't working on my main account.
I tried switching email addresses numerous times but it wouldn't send me any notifications until I made a new account.

**Comment by RoyalFlyBy** [comment] 2020-02-14 03:31
Testing it as we speak but it may be a few hours until it gets notified of a stream starting. 
Worst case scenario I will know by tomorrow morning whether or not it actually works.
(The repository doesn't exist yet as I still need to write a README for it, it will be made after initial testing.)

![CBW demo build 1](https://user-images.githubusercontent.com/50518899/74498986-a9689400-4ee2-11ea-8695-03949abae849.png)

**Comment by ghost** [comment] 2020-02-14 18:16
If it can help you, **@RoyalFlyBy**, I use _ProtonMail_: notifications come normally.

**Comment by RoyalFlyBy** [comment] 2020-02-15 20:12
Build 5 has some rough edges but it works, peculiarities such as it downloading a lot of files rather than just one file per model.
GUI is stuck for weird reasons but i can fix all that today or tomorrow.
As for the notifications issue, that's an issue caused at Chaturbate's end see link below.
https://www.ambercutie.com/forums/threads/followers-on-chaturbate-problem.26854/
I will check if my program supports protonmail, that one I haven't checked yet.

**Comment by RoyalFlyBy** [comment] 2020-02-16 07:21
Okay so I fixed the errors I encountered and it seems to be working 97% fine
3 issues are still present 2 of which I cant really solve as of yet (because they are Chaturbate's fault) and the third I can but it's not something that occurs often making it hard to test fixes.
That issue being that the thread that listens for emails can sometimes crash for no apparent reason... Testing a solution right now but it only happens once a day or so...

As for protonmail support, the program works using the standard IMAP protocol and since protonmail is end to end encrypted I wasn't sure if it would be supported.
Turns out that it should be supported but only by using the protonmail bridge as documented here:
https://protonmail.com/bridge/outlook2013#2

Tomorrow I will upload the program into a repository called ChaturbateWatcher, it really is a work of art in my opinion (yes I'm actually excited to release it!)

**Comment by ghost** [comment] 2020-02-16 12:46
These are _beautiful news_ 😍, @RoyalFlyBy!
A note: I **can't** use ProtonMail Bridge, 'cause it's only for paying costumers, so I'll change email provider for Chaturbate: can You please tell me which ones are the best? Consider that I **don't** have email clients downloaded to my pc (Outlook, Thuderbird, etc.): I consult email boxes _directly from the Web_. 
What do You recommend me?
A second perplexity: sometimes the model I follow is online, but the recording stops and I see these script: «_Model password protected_» and there's also written «_anti spambots is active for grey users_» with a numeric password to insert. 
Is there a connection between? 
Is there a solution with ChaturbateWatcher?

**Comment by RoyalFlyBy** [comment] 2020-02-16 20:31
It's done.
I will push out an update later to make the settings.json file more readable but it works as is right now.

**Comment by RoyalFlyBy** [comment] 2020-02-17 02:43
I never ran into this cases, do you run into those issues often and do you think you can reproduce them? 
I would like to test it because password stuff should be easy enough to fix.

I think the anti spambots would only occur if you download a huge amount of streams at the same time or in rapid succession. This program should have less of an issue because it actually logs in which ChaturbateDownloader doesn't.

As for email providers to use, I think Outlook would be the easiest but I actually only tested Gmail actively. U don't have to download a email client for the program; it has one embedded. Just need the IMAP details that the web ones provide for compatibility purposes.

**Comment by ghost** [comment] 2020-02-17 17:33
I'm really happy and grateful to You for creating the new .exe: I think it'll take me _a long time_ to figure out how to make it work😧! F.e.: I **can't** use ProtonMail Bridge 'cause I've a free account (it'is only for pay-users, it's slow and it has some bugs, I've read) and I **can't** use Microsoft Outlook 'cause not freeware. The only option is create a Gmail account from [here](https://accounts.google.com/signup/v2/webcreateaccount?hl=en&flowName=GlifWebSignIn&flowEntry=SignUp), I suppose. What annoys me is _the verification by phone number_. 
You wrote:

> U don't have to download a email client for the program; it has one embedded. Just need the IMAP details that the web ones provide for compatibility purposes.

But [this webpage](https://support.google.com/mail/answer/7126229?hl=en) explicitly mentions the pre-existence of an email client installed on PC (Step 2). I don't have any client. I'm confused; sorry my incompetence, please😣...
About Your question:

> I never ran into this cases, do you run into those issues often and do you think you can reproduce them? I would like to test it because password stuff should be easy enough to fix.

No, it only happened _once_, **@RoyalFlyby**: I really don't know if I can reproduce.

**Comment by RoyalFlyBy** [comment] 2020-02-17 17:49
> Microsoft Outlook not freeware

https://signup.live.com/signup
Maybe their offline email client itself isn't free (nit sure, never used) but simple account creation is free? (their email service keeps changing name, used to be Hotmail, then Live now it's called Outlook too)

> this webpage explicitly mentions the pre-existence of an email client installed on PC (Step 2). 

I can see how this is confusing but I will try my best to lead you through the process
The program has one built-in, so instead of giving an email client the IMAP details we put them inside settings.json

For Gmail I believe their server is imap.gmail.com on port 993, found on that same webpage you referenced

so what we do is we make settings.json look like this then
```
{
    "imapHost": "imap.gmail.com",
    "imapPort": 993,
    "ssl" true,
    "email": "example@gmail.com",
    "password": "password4example"
}
```
As you can see, regularly you would put that information in the "email client" but now instead we put it in the settings.json so the built-in email client takes care of it

**Comment by ghost** [comment] 2020-02-20 14:17
You're right, **@RoyalFlyBy**: I confused the email box (_freeware_) with the email client (_paid_). Following the example, I opened a GMailbox exclusively for this purpose, using the code You reported, with the addition of some detail present in the .json file:
```
{
    "imapHost": "imap.example.com",
    "imapPort": 993,
    "ssl": true, 
    "email": "example@gmail.com", 
    "password": "password4example", 
    "mailbox": "INBOX",
    "emailInterval": 60,
    "ffmpegPath": "ffmpeg",
    "debug": false
}
```
Now I'm waiting to see if notifications arrive or not: so far no notifications have arrived, only trivial advertisements from Chaturbate. This should mean that the mailbox works, I suppose.

**Comment by RoyalFlyBy** [comment] 2020-02-20 15:08
One thing I did notice is the email listener thread kills itself after 24 hours exact. I tried to work around it but for nor it has to be restarted every day just in case.
That and storage might become a problem, in my sleep it downloaded 20gb 😂😂.

Good to hear you figured out how to use it, enjoy and let me know about other future improvements.

**Comment by ghost** [comment] 2020-02-21 14:18
Today I did the first test and _there's something I must have been wrong_ 😞. All notifications arrive correctly at my GMailbox and the .json file's setting should be correct too. However, when I start the program, after a minute the prompt says:
![1st Proof](https://user-images.githubusercontent.com/58144783/75041316-a0685b80-54bc-11ea-923c-1a7785c679bb.png)
I also tried to create an Outlook mailbox, using the same code above changing email and password.
```
{
    "imapHost": "imap.example.com",
    "imapPort": 993,
    "ssl": true, 
    "email": "example@outlook.com", 
    "password": "password4example", 
    "mailbox": "INBOX",
    "emailInterval": 60,
    "ffmpegPath": "ffmpeg",
    "debug": false
}
```
It gives me **the same error**.
It works for You and not for me: please, help me, @RoyalFlyBy 😭!

**Comment by RoyalFlyBy** [comment] 2020-02-23 00:52
The error message in the command prompt is in a language I don't understand, Could you translate that for me?

The IP it tries to connect to is ```31.199.53.9```, this IP to my knowledge doesn't run an IMAP service or even belong to a mail provider.
That said it does seem to be hosting some site that redirects to ```cortesia.tim.it (on 31.199.53.11)``` which is owned by TIM the internet service provider? ```m.tim.it``` but I believe you said you were using Gmail/Outlook and neither have anything to do with a random Italian ISP :/

Show me your settings.json (just copy-paste), censor your email and password.
I believe you may have made typo in the host option.
Or maybe your ISP is trying to intercept the connection?

Tomorrow I will (~13:00 Chicago timezone) be releasing an update that brings several improvements, one very crucial improvement is the email listener thread and new logging for it. It will help us solve this problem.

**Comment by ghost** [comment] 2020-02-23 10:05
Oh, sorry😧@RoyalFlyBy! The writing is in my native language and says: «_impossibile stabilire la connessione. Risposta non corretta della parte connessa dopo l'intervallo di tempo oppure mancata risposta dall'host collegato_», in English «**could not establish connection. Incorrect response of the connected party after the time interval or no response from the connected host**».

> I believe you said you were using Gmail/Outlook and neither have anything to do with a random Italian ISP

I moved to Croatia but I'm Italian🇮🇹; my modem was made by my ISP -the main of Italy-: ([TIM](https://m.tim.it/)). But yes, I'm using a Gmail/Outlook account. 

> Show me your settings.json (just copy-paste), censor your email and password.

This is the .json file:
```
{
    "imapHost": "imap.example.com",
    "imapPort": 993,
    "ssl": true, 
    "email": "XXXXXXXXXXX@gmail.com", 
    "password": "XXXXXXXXXXXXXXXX", 
    "mailbox": "INBOX",
    "emailInterval": 60,
    "ffmpegPath": "ffmpeg",
    "debug": false
}
```
> Or maybe your ISP is trying to intercept the connection?

Insidious question: **I have no idea**. The other programs you have created work perfectly, as well as eMule and μTorrent, so I don't understand why TIM should try to intercept my connection(s) with GMail/Outlook.

**Comment by RoyalFlyBy** [comment] 2020-02-23 18:11
> ```
>{
>  "imapHost": "imap.example.com",
>   "imapPort": 993,
>   "ssl": true, 
>   "email": "XXXXXXXXXXX@gmail.com", 
>    "password": "XXXXXXXXXXXXXXXX", 
>   "mailbox": "INBOX",
>   "emailInterval": 60,
>    "ffmpegPath": "ffmpeg",
>   "debug": false
>}
>```
Should be:
```
{
    "imapHost": "imap.gmail.com",
    "imapPort": 993,
    "ssl": true, 
    "email": "XXXXXXXXXXX@gmail.com", 
    "password": "XXXXXXXXXXXXXXXX", 
    "mailbox": "INBOX",
    "emailInterval": 60,
    "ffmpegPath": "ffmpeg",
    "debug": false
}
```
The change being replacing ```example``` with ```gmail``` to make it the IMAP host ```imap.gmail.com``` which would be the URL found on the Gmail guide page.

**Comment by RoyalFlyBy** [comment] 2020-02-24 07:59
Update is half a day late but in return I found a crucial bug and added a cool feature.

**Comment by ghost** [comment] 2020-02-24 16:42
But it's true, You're right, **@Royalflyby**: I completely kept misinterpreting the IMAP host' function and the correct way to compile it, really doing honor to my nickname of «_dummy_»🤣! What an idiot I'm ...

You've done well in specifying to enable insecure app access in GMail, as well as advising to create a GMailbox dedicated: today I did the first successful test **with full success**, after manually enable it!!! 
Many thanks for Your patience.

**Comment by RoyalFlyBy** [comment] 2020-02-24 17:42
Great to hear that it finally works! 
This was your first time dealing with IMAP?
If so don't take it too hard it happens, this first time I was dealing with IMAP I was lost too

I hope you saved some storage space because 
these streams can quickly add up.

On top of that I dont recommend having too many followed models, watching 3 streams at the same time isn't as suspicious as watching 20 at the same time 😅

Other than that, do you have any other feature requests I may have forgotten?

**Comment by ghost** [comment] 2020-02-25 15:37
Thanks for Your interest, **@RoyalFlyBy**!

> On top of that I dont recommend having too many followed models, watching 3 streams at the same time isn't as suspicious as watching 20 at the same time.

Actually, I only follow two models.

Since I don't have an account with tokens, I can't help You with the interruption problem when it goes into "_private video_" mode: I'm sorry. However, I'll continue to test these days ...

And **thank You very much for Your work**😃!

**Comment by RoyalFlyBy** [comment] 2020-02-26 05:15
No problem, it was a good practice project for something else I really do need to code.

I will close this issue since ChaturbateWatcher is almost entirely done, new issues will be there anyways.

Enjoy the program and don't run out of space. (happened to me earlier today, had to move 120gb of data to an external storage device)

**Closed as completed by RoyalFlyBy** 2020-02-26 05:15 UTC
Labels: enhancement
